### ISSUE TITLE
Write JSON

### ISSUE THREAD

**Issue by truongsinh** [EnterpriseDB/mongo_fdw#10]
Hi,

I made a new feature in this commit https://github.com/truongsinh/mongo_fdw/commit/61e6b73abc337b35990ce88c73b558c1cf4a412c , which allows FDW to write JSON back to Mongo. However, there are some compiling warnings; users have to go to `json-c`, `sh autogen.sh`, `./configure`, `make` first; and there are no unit tests. So i haven't made a PR yet, but it is working in our dev environment.

**Comment by ibrarahmad** [comment]
Commited
