### ISSUE TITLE
Join/Filter/Aggregate Push Down ?

### ISSUE THREAD

**Issue by GiannisDimitriou** [EnterpriseDB/mongo_fdw#122]
Hi, does the computation of joining 2 collections  (#16) pushed down to mongodb?
What about filters and aggregates?

Thank You

**Comment by HolgerGH** [comment]
Hi, I would also be interested in these kind of questions. Is there a more detailed documentation?

**Comment by jeevanchalke** [comment]
The latest version of mongo_fdw 5.4.0 does have these pushdowns. So closing it.

If you get into any issues. feel free to open a new issue to work on.

Thanks
