### ISSUE TITLE
make fails for  mongo_fdw 

### ISSUE THREAD

**Issue by jduncanl** [EnterpriseDB/mongo_fdw#138]
Hi, 

 I am trying to install  mongo_fdw   on postgres  12.4
I get an error when I try to create the extension. 

**Operative system:** 
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

*version()*
PostgreSQL 12.4 (Ubuntu 12.4-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0, 64-bit

**Steps all run as root**
git clone https://github.com/EnterpriseDB/mongo_fdw.git   --recursive
cd mongo_fdw
 export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
export PATH=/usr/lib/postgresql/12/bin:$PATH

./autogen.sh --with-master 
Script output last  lines: 

make[2]: Leaving directory '/root/id/mongo_fdw/json-c'
make[1]: Leaving directory '/root/id/mongo_fdw/json-c'
Making install in tests
make[1]: Entering directory '/root/id/mongo_fdw/json-c/tests'
make[2]: Entering directory '/root/id/mongo_fdw/json-c/tests'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/root/id/mongo_fdw/json-c/tests'
make[1]: Leaving directory '/root/id/mongo_fdw/json-c/tests'
Done

>>So no errors
 extension "mongo_fdw" has no installation script nor update path for version "1.1"

>> If I return to the folder and try to install by hand I get the following error: 
make 

mongo_wrapper_meta.c:17:10: fatal error: mongoc.h: No such file or directory
   17 | #include

Thanks for helping.

**Comment by vaibhavdalvi93** [comment]
Thanks @jduncanl for reporting an issue.

This error is because path for mongoc.h file is unavailable in PKG_CONFIG_PATH.
`export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH`

The header file mongoc.h is available in mongo-c-driver source directory. 
I think, you need to export PKG_CONFIG_PATH as shown below,
`export PKG_CONFIG_PATH=mongo-c-driver/src/:mongo-c-driver/src/libbson/src`

You can export this after running autogen.sh successfully.

Let us know if you are still facing an issue.

**Comment by jduncanl** [comment]
> 
> 
> Thanks @jduncanl for reporting an issue.
> 
> This error is because path for mongoc.h file is unavailable in PKG_CONFIG_PATH.
> `export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH`
> 
> The header file mongoc.h is available in mongo-c-driver source directory.
> I think, you need to export PKG_CONFIG_PATH as shown below,
> `export PKG_CONFIG_PATH=mongo-c-driver/src/:mongo-c-driver/src/libbson/src`
> 
> You can export this after running autogen.sh successfully.
> 
> Let us know if you are still facing an issue.

Hi,
Thanks. I was able to solve it. Basically I compiled  SSL, then the driver, then run the configure script that found the driver already in place. That solved the issue. 

Best regards,
