### ISSUE TITLE
Installation problem in ubuntu 20.04

### ISSUE THREAD

**Issue by epaolillo** [EnterpriseDB/mongo_fdw#141]
** Installation steps

* git clone https://github.com/EnterpriseDB/mongo_fdw.git --recursive
* bash autogen.sh --with-master

(Result of compilation attached)
[compilation.txt](https://github.com/EnterpriseDB/mongo_fdw/files/5835891/compilation.txt)

Run postgres:

postgres=# CREATE EXTENSION mongo_fdw;
ERROR:  could not open extension control file "/usr/share/postgresql/12/extension/mongo_fdw.control": No such file or directory

If i copied manually the files from compilation folder to /usr/share/postgresql/12/extension/ i get:

postgres=# CREATE EXTENSION mongo_fdw;
ERROR:  could not access file "$libdir/mongo_fdw": No such file or directory

Thank you!!

**Comment by epaolillo** [comment]
I was forget do:
make
make install

**Comment by omkz** [comment]
@epaolillo did it work?
