### ISSUE TITLE
Issue on creating extension

### ISSUE THREAD

**Issue by aliabbasrizvi** [EnterpriseDB/mongo_fdw#143]
Hi

I am trying to create the extension on MacOS after the installation and get the following error:

```
postgres=# create extension mongo_fdw;
ERROR:  could not load library "/Applications/Postgres.app/Contents/Versions/13/lib/postgresql/mongo_fdw.so": dlopen(/Applications/Postgres.app/Contents/Versions/13/lib/postgresql/mongo_fdw.so, 10): Library not loaded: @rpath/libmongoc-1.0.0.dylib
  Referenced from: /Applications/Postgres.app/Contents/Versions/13/lib/postgresql/mongo_fdw.so
  Reason: image not found
```

Can you tell me what could be wrong? Did I miss a step?

Please let me know.

Thanks

**Comment by vaibhavdalvi93** [comment]
Thanks @aliabbasrizvi for reporting an issue.

Since, we don't support mongo_fdw on MacOS, haven't tested it.

Just looking at the error you provided looks like that libmongoc library is not available at required directory.

**Comment by aliabbasrizvi** [comment]
Hi @vaibhavdalvi93 . Thank you for getting back. I was able to get past this issue. Instead of `Postgres.app`, I was able to use `postgresql` from Homebrew.
