### ISSUE TITLE
Does it support joins?

### ISSUE THREAD

**Issue by saritasa** [EnterpriseDB/mongo_fdw#16]
Is it possible to "join" 2 collections in mongo though mongo_fdw sql layer?

**Comment by ahsanhadi** [comment]
On Wed, Jan 14, 2015 at 11:38 PM, saritasa <notifications@github.com> wrote:

> Is it possible to "join" 2 collections in mongo though mongo_fdw sql layer?
>

Do you mean join two foreign tables based on mongo collection?

—
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mongo_fdw/issues/16>.
>



-- 
Ahsan Hadi
Snr Director Product Development
EnterpriseDB Corporation
The Enterprise Postgres Company

Phone: +92-51-8358874
Mobile: +92-333-5162114

Website: www.enterprisedb.com
EnterpriseDB Blog: http://blogs.enterprisedb.com/
Follow us on Twitter: http://www.twitter.com/enterprisedb

This e-mail message (and any attachment) is intended for the use of the
individual or entity to whom it is addressed. This message contains
information from EnterpriseDB Corporation that may be privileged,
confidential, or exempt from disclosure under applicable law. If you are
not the intended recipient or authorized to receive this for the intended
recipient, any use, dissemination, distribution, retention, archiving, or
copying of this communication is strictly prohibited. If you have received
this e-mail in error, please notify the sender immediately by reply e-mail
and delete this message.

**Comment by saritasa** [comment]
correct

**Comment by ahsanhadi** [comment]
On Jan 15, 2015 11:28 PM, "saritasa" <notifications@github.com> wrote:
>
> correct
>

Yes that should work.
