### ISSUE TITLE
PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type json

### ISSUE THREAD

**Issue by CarlosEspejo** [EnterpriseDB/mongo_fdw#17]
For certain documents, I am getting this parse error (see below). I tried to sanitize the data in mongo and remove the control characters but no luck. Is there any tips you may have for dealing with this problem.

```
PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type json

DETAIL:  Character with value 0x19 must be escaped.

CONTEXT:  JSON data, line 1: ...Roslin Institute in Midlothian, one of the world ...
```

![screen shot 2015-01-20 at 3 09 17 pm](https://cloud.githubusercontent.com/assets/911741/5825797/1cfdd888-a0bc-11e4-8aad-f0286425c616.png)

**Comment by ahsanhadi** [comment]
Can you please share some sample data to help reproduce this issue?

On Wed, Jan 21, 2015 at 1:55 AM, Carlos.rb <notifications@github.com> wrote:

> For certain documents, I am getting this parse error (see below). I tried
> to sanitize the data in mongo and remove the control characters but no
> luck. Is there any tips you may have for dealing with this problem.
>
> PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type json
>
> DETAIL:  Character with value 0x19 must be escaped.
>
> CONTEXT:  JSON data, line 1: ...Roslin Institute in Midlothian, one of the world ...
>
> [image: screen shot 2015-01-20 at 3 09 17 pm]
> <https://cloud.githubusercontent.com/assets/911741/5825797/1cfdd888-a0bc-11e4-8aad-f0286425c616.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mongo_fdw/issues/17>.
>



-- 
Ahsan Hadi
Snr Director Product Development
EnterpriseDB Corporation
The Enterprise Postgres Company

Phone: +92-51-8358874
Mobile: +92-333-5162114

Website: www.enterprisedb.com
EnterpriseDB Blog: http://blogs.enterprisedb.com/
Follow us on Twitter: http://www.twitter.com/enterprisedb

This e-mail message (and any attachment) is intended for the use of the
individual or entity to whom it is addressed. This message contains
information from EnterpriseDB Corporation that may be privileged,
confidential, or exempt from disclosure under applicable law. If you are
not the intended recipient or authorized to receive this for the intended
recipient, any use, dissemination, distribution, retention, archiving, or
copying of this communication is strictly prohibited. If you have received
this e-mail in error, please notify the sender immediately by reply e-mail
and delete this message.

**Comment by CarlosEspejo** [comment]
Here's the JSON document from mongo look at the interaction.content node and the code \u0019

```
{
    "_id": {
        "$oid": "54bed66801d2c0648100028d"
    },
    "client": {
        "client_id": 6,
        "project_id": 8
    },
    "interaction": {
        "author": {
            "description": "N/A",
            "followers_count": "N/A",
            "friends_count": "N/A",
            "id": "dbc6b8e82a3de93ca0bad204ed8157ef",
            "lang": "N/A",
            "location": "N/A",
            "name": "N/A",
            "profile_image_url": "N/A",
            "screen_name": "N/A",
            "statuses_count": "N/A",
            "url": "N/A"
        },
        "content": "Prof Clark led the Roslin Institute in Midlothian, one of the world \u0019s leading animal biotechnology research centers.",
        "country": "N/A",
        "headline": "",
        "impressions": "N/A",
        "klout_score": "N/A",
        "language": "en",
        "publication_at": "Fri, 16 Jan 2015 00:49:21 +0000",
        "region": "N/A",
        "sentiment": -0.016,
        "source": "web",
        "translations": "N/A",
        "type": "facebook",
        "word_count": 7017
    },
    "pipeline_created_at": "2015-01-20 22:27:46 UTC",
    "pipeline_updated_at": "2015-01-20 22:27:46 UTC",
    "source_info": {
        "doc_id": "1e49d1982133ae80e066feb7df6e60cc",
        "hash": "19c1078dd9d91ab8e5189f4bc83074fc",
        "hash_type": "stream",
        "id": "1e49d1982133ae80e066feb7df6e60cc",
        "type": "facebook"
    },
    "subscriptionId": "c3180dc8a16e2dc43842a66bdc62bb85",
    "version": "1.0"
}
```
Here's the SQL statement that was generated when inserting the same json file from rails into a test table.

```
INSERT INTO "examples" ("data") VALUES ($1)  [["data", "{\"_id\":{\"$oid\":\"54bed66801d2c0648100028d\"},\"client\":{\"client_id\":6,\"project_id\":8},\"interaction\":{\"author\":{\"description\":\"N/A\",\"followers_count\":\"N/A\",\"friends_count\":\"N/A\",\"id\":\"dbc6b8e82a3de93ca0bad204ed8157ef\",\"lang\":\"N/A\",\"location\":\"N/A\",\"name\":\"N/A\",\"profile_image_url\":\"N/A\",\"screen_name\":\"N/A\",\"statuses_count\":\"N/A\",\"url\":\"N/A\"},\"content\":\"Prof Clark led the Roslin Institute in Midlothian, one of the world \\u0019s leading animal biotechnology research centers.\",\"country\":\"N/A\",\"headline\":\"\",\"impressions\":\"N/A\",\"klout_score\":\"N/A\",\"language\":\"en\",\"publication_at\":\"Fri, 16 Jan 2015 00:49:21 +0000\",\"region\":\"N/A\",\"sentiment\":-0.016,\"source\":\"web\",\"translations\":\"N/A\",\"type\":\"facebook\",\"word_count\":7017},\"pipeline_created_at\":\"2015-01-20 22:27:46 UTC\",\"pipeline_updated_at\":\"2015-01-20 22:27:46 UTC\",\"source_info\":{\"doc_id\":\"1e49d1982133ae80e066feb7df6e60cc\",\"hash\":\"19c1078dd9d91ab8e5189f4bc83074fc\",\"hash_type\":\"stream\",\"id\":\"1e49d1982133ae80e066feb7df6e60cc\",\"type\":\"facebook\"},\"subscriptionId\":\"c3180dc8a16e2dc43842a66bdc62bb85\",\"version\":\"1.0\"}"]]
``` 

In the second case it worked without issues because it escaped the special character correctly.

Thank you for your quick response.

**Comment by ahsanhadi** [comment]
Okay got it. Will fix it this week.


On Wed, Jan 21, 2015 at 11:43 PM, Carlos.rb <notifications@github.com>
wrote:

> Here's the JSON document from mongo look at the interaction.content node
> and the code \u0019
>
> {
>     "_id": {
>         "$oid": "54bed66801d2c0648100028d"
>     },
>     "client": {
>         "client_id": 6,
>         "project_id": 8
>     },
>     "interaction": {
>         "author": {
>             "description": "N/A",
>             "followers_count": "N/A",
>             "friends_count": "N/A",
>             "id": "dbc6b8e82a3de93ca0bad204ed8157ef",
>             "lang": "N/A",
>             "location": "N/A",
>             "name": "N/A",
>             "profile_image_url": "N/A",
>             "screen_name": "N/A",
>             "statuses_count": "N/A",
>             "url": "N/A"
>         },
>         "content": "Prof Clark led the Roslin Institute in Midlothian, one of the world \u0019s leading animal biotechnology research centers.",
>         "country": "N/A",
>         "headline": "",
>         "impressions": "N/A",
>         "klout_score": "N/A",
>         "language": "en",
>         "publication_at": "Fri, 16 Jan 2015 00:49:21 +0000",
>         "region": "N/A",
>         "sentiment": -0.016,
>         "source": "web",
>         "translations": "N/A",
>         "type": "facebook",
>         "word_count": 7017
>     },
>     "pipeline_created_at": "2015-01-20 22:27:46 UTC",
>     "pipeline_updated_at": "2015-01-20 22:27:46 UTC",
>     "source_info": {
>         "doc_id": "1e49d1982133ae80e066feb7df6e60cc",
>         "hash": "19c1078dd9d91ab8e5189f4bc83074fc",
>         "hash_type": "stream",
>         "id": "1e49d1982133ae80e066feb7df6e60cc",
>         "type": "facebook"
>     },
>     "subscriptionId": "c3180dc8a16e2dc43842a66bdc62bb85",
>     "version": "1.0"
> }
>
> Here's the SQL statement that was generated when inserting the same json
> file from rails into a test table.
>
> INSERT INTO "examples" ("data") VALUES ($1)  [["data", "{\"_id\":{\"$oid\":\"54bed66801d2c0648100028d\"},\"client\":{\"client_id\":6,\"project_id\":8},\"interaction\":{\"author\":{\"description\":\"N/A\",\"followers_count\":\"N/A\",\"friends_count\":\"N/A\",\"id\":\"dbc6b8e82a3de93ca0bad204ed8157ef\",\"lang\":\"N/A\",\"location\":\"N/A\",\"name\":\"N/A\",\"profile_image_url\":\"N/A\",\"screen_name\":\"N/A\",\"statuses_count\":\"N/A\",\"url\":\"N/A\"},\"content\":\"Prof Clark led the Roslin Institute in Midlothian, one of the world \\u0019s leading animal biotechnology research centers.\",\"country\":\"N/A\",\"headline\":\"\",\"impressions\":\"N/A\",\"klout_score\":\"N/A\",\"language\":\"en\",\"publication_at\":\"Fri, 16 Jan 2015 00:49:21 +0000\",\"region\":\"N/A\",\"sentiment\":-0.016,\"source\":\"web\",\"translations\":\"N/A\",\"type\":\"facebook\",\"word_count\":7017},\"pipeline_created_at\":\"2015-01-20 22:27:46 UTC\",\"pipeline_updated_at\":\"2015-01-20 22:27:4
>  6 UTC\",
>  \"source_info\":{\"doc_id\":\"1e49d1982133ae80e066feb7df6e60cc\",\"hash\":\"19c1078dd9d91ab8e5189f4bc83074fc\",\"hash_type\":\"stream\",\"id\":\"1e49d1982133ae80e066feb7df6e60cc\",\"type\":\"facebook\"},\"subscriptionId\":\"c3180dc8a16e2dc43842a66bdc62bb85\",\"version\":\"1.0\"}"]]
>
> In the second case it worked without issues because it escaped the special
> character correctly.
>
> Thank you for your quick response.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mongo_fdw/issues/17#issuecomment-70895782>
> .
>



-- 
Ahsan Hadi
Snr Director Product Development
EnterpriseDB Corporation
The Enterprise Postgres Company

Phone: +92-51-8358874
Mobile: +92-333-5162114

Website: www.enterprisedb.com
EnterpriseDB Blog: http://blogs.enterprisedb.com/
Follow us on Twitter: http://www.twitter.com/enterprisedb

This e-mail message (and any attachment) is intended for the use of the
individual or entity to whom it is addressed. This message contains
information from EnterpriseDB Corporation that may be privileged,
confidential, or exempt from disclosure under applicable law. If you are
not the intended recipient or authorized to receive this for the intended
recipient, any use, dissemination, distribution, retention, archiving, or
copying of this communication is strictly prohibited. If you have received
this e-mail in error, please notify the sender immediately by reply e-mail
and delete this message.

**Comment by ibrarahmad** [comment]
I am able to select data after removing the special character. You can also
escape the special character in MongoDB.



MongoDB insert after removing special character

---------------------------------------------------

db.test.insert(

{

    "client": {
        "client_id": 6,
        "project_id": 8
    },
    "interaction": {
        "author": {
            "description": "N/A",
            "followers_count": "N/A",
            "friends_count": "N/A",
            "id": "dbc6b8e82a3de93ca0bad204ed8157ef",
            "lang": "N/A",
            "location": "N/A",
            "name": "N/A",
            "profile_image_url": "N/A",
            "screen_name": "N/A",
            "statuses_count": "N/A",
            "url": "N/A"
        },
        "content": "Prof Clark led the Roslin Institute in Midlothian,
one of the world  leading animal biotechnology research centers.",

        "country": "N/A",
        "headline": "",
        "impressions": "N/A",
        "klout_score": "N/A",
        "language": "en",
        "publication_at": "Fri, 16 Jan 2015 00:49:21 +0000",
        "region": "N/A",
        "sentiment": -0.016,
        "source": "web",
        "translations": "N/A",
        "type": "facebook",
        "word_count": 7017
    },
    "pipeline_created_at": "2015-01-20 22:27:46 UTC",
    "pipeline_updated_at": "2015-01-20 22:27:46 UTC",
    "source_info": {
        "doc_id": "1e49d1982133ae80e066feb7df6e60cc",
        "hash": "19c1078dd9d91ab8e5189f4bc83074fc",
        "hash_type": "stream",
        "id": "1e49d1982133ae80e066feb7df6e60cc",
        "type": "facebook"
    },
    "subscriptionId": "c3180dc8a16e2dc43842a66bdc62bb85",
    "version": "1.0"
}

);


mongo_fdw select statement
---------------------------

postgres=# select * from examples;
           _id            | version |
client
|


interaction



| created_at | updated_at
--------------------------+---------+----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------+------------+------------
 54cb688aae3706495aed8af6 | 1.0     |
{"client_id":6.000000,"project_id":8.000000} |
{"author":{"description":"N/A","followers_count":"N/A","friends_count":"N/A","id":"dbc6b8e82a3de93ca0bad204ed8157ef","la
ng":"N/A","location":"N/A","name":"N/A","profile_image_url":"N/A","screen_name":"N/A","statuses_count":"N/A","url":"N/A"},"content":"Prof
Clark led the Roslin Institute in Midlothian, one of the world  lea
ding animal biotechnology research
centers.","country":"N/A","headline":"","impressions":"N/A","klout_score":"N/A","language":"en","publication_at":"Fri,
16 Jan 2015 00:49:21 +0000","region":"N/A","sentime
nt":-0.016000,"source":"web","translations":"N/A","type":"facebook","word_count":7017.000000}
|            |
(1 row)

postgres=# select interaction from examples;


interaction


-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
----------
 {"author":{"description":"N/A","followers_count":"N/A","friends_count":"N/A","id":"dbc6b8e82a3de93ca0bad204ed8157ef","lang":"N/A","location":"N/A","name":"N/A","profile_image_url":"N/A","screen_name":"N/A
","statuses_count":"N/A","url":"N/A"},"content":"Prof Clark led the Roslin
Institute in Midlothian, one of the world  leading animal biotechnology
research centers.","country":"N/A","headline":"","impressi
ons":"N/A","klout_score":"N/A","language":"en","publication_at":"Fri, 16
Jan 2015 00:49:21
+0000","region":"N/A","sentiment":-0.016000,"source":"web","translations":"N/A","type":"facebook","word_count":701
7.000000}
(1 row)















MongoDB Insert with special character.
--------------------------------------

db.test.insert(

{

    "client": {
        "client_id": 6,
        "project_id": 8
    },
    "interaction": {
        "author": {
            "description": "N/A",
            "followers_count": "N/A",
            "friends_count": "N/A",
            "id": "dbc6b8e82a3de93ca0bad204ed8157ef",
            "lang": "N/A",
            "location": "N/A",
            "name": "N/A",
            "profile_image_url": "N/A",
            "screen_name": "N/A",
            "statuses_count": "N/A",
            "url": "N/A"
        },
        "content": "Prof Clark led the Roslin Institute in Midlothian,
one of the world \\u0019s leading animal biotechnology research
centers.",

        "country": "N/A",
        "headline": "",
        "impressions": "N/A",
        "klout_score": "N/A",
        "language": "en",
        "publication_at": "Fri, 16 Jan 2015 00:49:21 +0000",
        "region": "N/A",
        "sentiment": -0.016,
        "source": "web",
        "translations": "N/A",
        "type": "facebook",
        "word_count": 7017
    },
    "pipeline_created_at": "2015-01-20 22:27:46 UTC",
    "pipeline_updated_at": "2015-01-20 22:27:46 UTC",
    "source_info": {
        "doc_id": "1e49d1982133ae80e066feb7df6e60cc",
        "hash": "19c1078dd9d91ab8e5189f4bc83074fc",
        "hash_type": "stream",
        "id": "1e49d1982133ae80e066feb7df6e60cc",
        "type": "facebook"
    },
    "subscriptionId": "c3180dc8a16e2dc43842a66bdc62bb85",
    "version": "1.0"
}

);

mongo_fdw select statement
---------------------------


postgres=# select * from examples;
           _id            | version |
client
|


interaction



| created_at | updated_at
--------------------------+---------+----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------+------------+------------
 54cb6617ae3706495aed8af4 | 1.0     |
{"client_id":6.000000,"project_id":8.000000} |
{"author":{"description":"N/A","followers_count":"N/A","friends_count":"N/A","id":"dbc6b8e82a3de93ca0bad204ed8157ef","la
ng":"N/A","location":"N/A","name":"N/A","profile_image_url":"N/A","screen_name":"N/A","statuses_count":"N/A","url":"N/A"},"content":"Prof
Clark led the Roslin Institute in Midlothian, one of the world \\u0
019s leading animal biotechnology research
centers.","country":"N/A","headline":"","impressions":"N/A","klout_score":"N/A","language":"en","publication_at":"Fri,
16 Jan 2015 00:49:21 +0000","region":"N/A",
"sentiment":-0.016000,"source":"web","translations":"N/A","type":"facebook","word_count":7017.000000}
|            |
(1 row)

postgres=# select interaction from examples;



interaction




-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------
 {"author":{"description":"N/A","followers_count":"N/A","friends_count":"N/A","id":"dbc6b8e82a3de93ca0bad204ed8157ef","lang":"N/A","location":"N/A","name":"N/A","profile_image_url":"N/A","screen_name":"N/A
","statuses_count":"N/A","url":"N/A"},"content":"Prof Clark led the Roslin
Institute in Midlothian, one of the world \\u0019s leading animal
biotechnology research centers.","country":"N/A","headline":"","
impressions":"N/A","klout_score":"N/A","language":"en","publication_at":"Fri,
16 Jan 2015 00:49:21
+0000","region":"N/A","sentiment":-0.016000,"source":"web","translations":"N/A","type":"facebook","word_co
unt":7017.000000}
(1 row)










On Mon, Jan 26, 2015 at 2:10 PM, Ahsan Hadi <notifications@github.com>
wrote:

> Okay got it. Will fix it this week.
>
>
> On Wed, Jan 21, 2015 at 11:43 PM, Carlos.rb <notifications@github.com>
> wrote:
>
> > Here's the JSON document from mongo look at the interaction.content node
> > and the code \u0019
> >
> > {
> > "_id": {
> > "$oid": "54bed66801d2c0648100028d"
> > },
> > "client": {
> > "client_id": 6,
> > "project_id": 8
> > },
> > "interaction": {
> > "author": {
> > "description": "N/A",
> > "followers_count": "N/A",
> > "friends_count": "N/A",
> > "id": "dbc6b8e82a3de93ca0bad204ed8157ef",
> > "lang": "N/A",
> > "location": "N/A",
> > "name": "N/A",
> > "profile_image_url": "N/A",
> > "screen_name": "N/A",
> > "statuses_count": "N/A",
> > "url": "N/A"
> > },
> > "content": "Prof Clark led the Roslin Institute in Midlothian, one of
> the world \u0019s leading animal biotechnology research centers.",
> > "country": "N/A",
> > "headline": "",
> > "impressions": "N/A",
> > "klout_score": "N/A",
> > "language": "en",
> > "publication_at": "Fri, 16 Jan 2015 00:49:21 +0000",
> > "region": "N/A",
> > "sentiment": -0.016,
> > "source": "web",
> > "translations": "N/A",
> > "type": "facebook",
> > "word_count": 7017
> > },
> > "pipeline_created_at": "2015-01-20 22:27:46 UTC",
> > "pipeline_updated_at": "2015-01-20 22:27:46 UTC",
> > "source_info": {
> > "doc_id": "1e49d1982133ae80e066feb7df6e60cc",
> > "hash": "19c1078dd9d91ab8e5189f4bc83074fc",
> > "hash_type": "stream",
> > "id": "1e49d1982133ae80e066feb7df6e60cc",
> > "type": "facebook"
> > },
> > "subscriptionId": "c3180dc8a16e2dc43842a66bdc62bb85",
> > "version": "1.0"
> > }
> >
> > Here's the SQL statement that was generated when inserting the same json
> > file from rails into a test table.
> >
> > INSERT INTO "examples" ("data") VALUES ($1) [["data",
> "{\"_id\":{\"$oid\":\"54bed66801d2c0648100028d\"},\"client\":{\"client_id\":6,\"project_id\":8},\"interaction\":{\"author\":{\"description\":\"N/A\",\"followers_count\":\"N/A\",\"friends_count\":\"N/A\",\"id\":\"dbc6b8e82a3de93ca0bad204ed8157ef\",\"lang\":\"N/A\",\"location\":\"N/A\",\"name\":\"N/A\",\"profile_image_url\":\"N/A\",\"screen_name\":\"N/A\",\"statuses_count\":\"N/A\",\"url\":\"N/A\"},\"content\":\"Prof
> Clark led the Roslin Institute in Midlothian, one of the world \\u0019s
> leading animal biotechnology research
> centers.\",\"country\":\"N/A\",\"headline\":\"\",\"impressions\":\"N/A\",\"klout_score\":\"N/A\",\"language\":\"en\",\"publication_at\":\"Fri,
> 16 Jan 2015 00:49:21
> +0000\",\"region\":\"N/A\",\"sentiment\":-0.016,\"source\":\"web\",\"translations\":\"N/A\",\"type\":\"facebook\",\"word_count\":7017},\"pipeline_created_at\":\"2015-01-20
> 22:27:46 UTC\",\"pipeline_updated_at\":\"2015-01-20 22:27:4
> > 6 UTC\",
> >
> \"source_info\":{\"doc_id\":\"1e49d1982133ae80e066feb7df6e60cc\",\"hash\":\"19c1078dd9d91ab8e5189f4bc83074fc\",\"hash_type\":\"stream\",\"id\":\"1e49d1982133ae80e066feb7df6e60cc\",\"type\":\"facebook\"},\"subscriptionId\":\"c3180dc8a16e2dc43842a66bdc62bb85\",\"version\":\"1.0\"}"]]
>
> >
> > In the second case it worked without issues because it escaped the
> special
> > character correctly.
> >
> > Thank you for your quick response.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/EnterpriseDB/mongo_fdw/issues/17#issuecomment-70895782>
>
> > .
> >
>
>
>
> --
> Ahsan Hadi
> Snr Director Product Development
> EnterpriseDB Corporation
> The Enterprise Postgres Company
>
> Phone: +92-51-8358874
> Mobile: +92-333-5162114
>
> Website: www.enterprisedb.com
> EnterpriseDB Blog: http://blogs.enterprisedb.com/
> Follow us on Twitter: http://www.twitter.com/enterprisedb
>
> This e-mail message (and any attachment) is intended for the use of the
> individual or entity to whom it is addressed. This message contains
> information from EnterpriseDB Corporation that may be privileged,
> confidential, or exempt from disclosure under applicable law. If you are
> not the intended recipient or authorized to receive this for the intended
> recipient, any use, dissemination, distribution, retention, archiving, or
> copying of this communication is strictly prohibited. If you have received
> this e-mail in error, please notify the sender immediately by reply e-mail
> and delete this message.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mongo_fdw/issues/17#issuecomment-71431511>
> .
>



-- 
Ibrar Ahmed

**Comment by ahsanhadi** [comment]
Is this still an active issue?

**Comment by CarlosEspejo** [comment]
Cleaning the data in mongo was the only work around I could use, but its not the ideal solution.
