### ISSUE TITLE
PostgreSQL 10, 11, 12, 13, 14, or 15 is required to compile this extension

### ISSUE THREAD

**Issue by MihaiRaduSandu** [EnterpriseDB/mongo_fdw#175]
Hello,

I tried installing mongo_fdw on centos 7 with a running postresql 15.5, both with autogen.sh and also with manual installation but when I run make install I receive this error:
Makefile:46: *** PostgreSQL 10, 11, 12, 13, 14, or 15 is required to compile this extension.  Stop.

Also, if trying to install the package with yum, it fails with missing package:
Requires: pgdg-libmongoc-libs

Can you help me with some stepts to correctly install it, please? 

cp_config returns:
`BINDIR = /usr/pgsql-15/bin
DOCDIR = /usr/pgsql-15/doc
HTMLDIR = /usr/pgsql-15/doc/html
INCLUDEDIR = /usr/pgsql-15/include
PKGINCLUDEDIR = /usr/pgsql-15/include
INCLUDEDIR-SERVER = /usr/pgsql-15/include/server
LIBDIR = /usr/pgsql-15/lib
PKGLIBDIR = /usr/pgsql-15/lib
LOCALEDIR = /usr/pgsql-15/share/locale
MANDIR = /usr/pgsql-15/share/man
SHAREDIR = /usr/pgsql-15/share
SYSCONFDIR = /etc/sysconfig/pgsql
PGXS = /usr/pgsql-15/lib/pgxs/src/makefiles/pgxs.mk
CONFIGURE =  '--enable-rpath' '--prefix=/usr/pgsql-15' '--includedir=/usr/pgsql-15/include' '--mandir=/usr/pgsql-15/share/man' '--datadir=/usr/pgsql-15/share' '--libdir=/usr/pgsql-15/lib' '--with-lz4' '--with-zstd' '--enable-tap-tests' '--with-icu' '--with-llvm' '--with-perl' '--with-python' '--with-tcl' '--with-tclconfig=/usr/lib64' '--with-openssl' '--with-pam' '--with-gssapi' '--with-includes=/usr/include' '--with-libraries=/usr/lib64' '--enable-nls' '--enable-dtrace' '--with-uuid=e2fs' '--with-libxml' '--with-libxslt' '--with-ldap' '--with-selinux' '--with-systemd' '--with-system-tzdata=/usr/share/zoneinfo' '--sysconfdir=/etc/sysconfig/pgsql' '--docdir=/usr/pgsql-15/doc' '--htmldir=/usr/pgsql-15/doc/html' 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' 'LDFLAGS=-Wl,--as-needed' 'LLVM_CONFIG=/usr/lib64/llvm5.0/bin/llvm-config' 'CLANG=/opt/rh/llvm-toolset-7/root/usr/bin/clang' 'PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig' 'PYTHON=/usr/bin/python3'
CC = gcc -std=gnu99
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -L/usr/lib64/llvm5.0/lib -L/usr/lib64 -Wl,--as-needed -Wl,-rpath,'/usr/pgsql-15/lib',--enable-new-dtags
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lselinux -lzstd -llz4 -lxslt -lxml2 -lpam -lssl -lcrypto -lgssapi_krb5 -lz -lreadline -lpthread -lrt -ldl -lm 
VERSION = PostgreSQL 15.5
`
Thank you,
Mihai

**Comment by vaibhavdalvi93** [comment]
Thanks, @MihaiRaduSandu for reporting an issue.

> Makefile:46: *** PostgreSQL 10, 11, 12, 13, 14, or 15 is required to compile this extension. Stop.

Could you please make sure to export the PATH variable with PostgreSQL bin directory E.g. 
`export PATH=/usr/local/pgsql/bin/:$PATH`

For installation, please follow the steps mentioned in README file [here](https://github.com/EnterpriseDB/mongo_fdw#installation).

Please let us know if you are still facing an issue.

**Comment by MihaiRaduSandu** [comment]
Hello,

I managed to install it, finally. This time it went very smooth and I didn't have any issues.
I think my mistake the previous time was I didn't do the entire installation process within root (sudo su), some of the steps I was just trying to run with sudo, Also possibly the path was only set up on my user and not on the root user as well, and anyway I discovered that the puppet was deleting the path :)

Thank you for your support and a happy new year,
Mihai
