### ISSUE TITLE
--authenticationDatabase? 

### ISSUE THREAD

**Issue by ghost** [EnterpriseDB/mongo_fdw#26]
So, will you support this option since the new version of mongo requires this if you're using authentication?  If you do already support it, how do we pass in the options and where?

**Comment by ahsanhadi** [comment]
This is not supported yet...we will add this option asap.

**Comment by ibrarahmad** [comment]
The authenticationDatabase is a command line option to use with Mongo Clients. 

Ref: http://docs.mongodb.org/manual/reference/program/mongo/
...
--authenticationDatabase <dbname>
New in version 2.4.

Specifies the database that holds the user’s credentials.

If you do not specify a value for --authenticationDatabase, mongo uses the database specified in the connection string.
...



In Meta driver the connection string "URI" already has database option, so it should work.
