### ISSUE TITLE
$geoWithin support?

### ISSUE THREAD

**Issue by devTristan** [EnterpriseDB/mongo_fdw#28]
```sql
SELECT * FROM foreign_mongo_table WHERE $geoWithin(the_geom, [ polygon ]);
```

Is there a way to do this?

**Comment by ahsanhadi** [comment]
Is this issue resolved? Do you still want us to take a look at this?

**Comment by devTristan** [comment]
I assumed it wouldn't be answered since it was a bit old, but I'm still very curious.
