### ISSUE TITLE
Setting Up mongo_fdw On Windows

### ISSUE THREAD

**Issue by enockbrk** [EnterpriseDB/mongo_fdw#29]
Hi,

I have a problem installing mongo_fdw on windows. Kindly help since i cant find sufficient documentation online as well. Please take me through the steps from when we download the extension, installation, configuration then usage.
Thanks

**Comment by dfloresgonz** [comment]
anyone??

**Comment by jasoncdavis0** [comment]
Please see some related information in https://github.com/EnterpriseDB/mongo_fdw/issues/21 - the team will be working on a windows installer later this year, although they'll help out here as they can.

**Comment by ahsanhadi** [comment]
Duplicate https://github.com/EnterpriseDB/mongo_fdw/issues/21
