### ISSUE TITLE
invalid option "username"

### ISSUE THREAD

**Issue by jney** [EnterpriseDB/mongo_fdw#30]
i'm following the `README`, but got this error while creating a user : 

```
-- create user mapping
CREATE USER MAPPING FOR postgres
         SERVER mongo_server
         OPTIONS (username 'mongo_user', password 'mongo_pass');
```

gives 

```
ERROR:  HV00D: invalid option "username"
HINT:  Valid options in this context are:
LOCATION:  mongo_fdw_validator, mongo_fdw.c:147
```

**Comment by jney** [comment]
i used this docker image : https://github.com/connexio-labs/docker-postgres which seems to an older version of `mongo_fdw` based on the original vesion `citusdata/mongo_fdw`

**Comment by jney** [comment]
i actually got the same issue using `3.0`. 

version showed is `1.0`  

```
localhost/db=# select extversion from pg_extension where extname='mongo_fdw';
 extversion
------------
 1.0
(1 row)
```

**Comment by ahsanhadi** [comment]
Hi Jean,

It seems that you are getting mongodb_fdw from the wrong location. Can you
please download the one that is available on enterprisedb github page, link
given below :

https://github.com/EnterpriseDB/mongo_fdw

I just tried and it is working fine following the instructions given on the
github page.

-- Ahsan


On Sun, May 24, 2015 at 12:38 AM, Jean-Sébastien Ney <
notifications@github.com> wrote:

> i actually got the same issue using 3.0.
>
> version showed is 1.0
>
> localhost/db=# select extversion from pg_extension where extname='mongo_fdw';
>  extversion
> ------------
>  1.0
> (1 row)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mongo_fdw/issues/30#issuecomment-104938540>
> .
>



-- 
Ahsan Hadi
Snr Director Product Development
EnterpriseDB Corporation
The Enterprise Postgres Company

Phone: +92-51-8358874
Mobile: +92-333-5162114

Website: www.enterprisedb.com
EnterpriseDB Blog: http://blogs.enterprisedb.com/
Follow us on Twitter: http://www.twitter.com/enterprisedb

This e-mail message (and any attachment) is intended for the use of the
individual or entity to whom it is addressed. This message contains
information from EnterpriseDB Corporation that may be privileged,
confidential, or exempt from disclosure under applicable law. If you are
not the intended recipient or authorized to receive this for the intended
recipient, any use, dissemination, distribution, retention, archiving, or
copying of this communication is strictly prohibited. If you have received
this e-mail in error, please notify the sender immediately by reply e-mail
and delete this message.

**Comment by jney** [comment]
is it ? https://github.com/connexio-labs/docker-postgres/blob/master/Dockerfile#L48
i'll try again.

**Comment by ahsanhadi** [comment]
As mentioned upthread, you need to download the code form enterprisedb github

https://github.com/EnterpriseDB/mongo_fdw
