### ISSUE TITLE
Full document retrieval

### ISSUE THREAD

**Issue by ssimeonov** [EnterpriseDB/mongo_fdw#32]
`mongo_fdw` is great for ETL and interactive analytics with one catch: the current schema mapping approach does not seem to allow any way for all the data in a document to be retrieved without _a priori_ knowing all top-level field names, which is important when _all_ Mongo data must become available in SQL. Adding this capability would substantially increase the power of `mongo_fdw`.

One simple approach would be to reserve a special JSON field name, e.g., `__doc` for the contents of the entire document. Then, one could get the best of schema-based and schema-less processing, e.g., 

```sql
CREATE FOREIGN TABLE docs(
    _id NAME,
    author text,
    created_at timestamptz,
    updated_at timestamptz,
    __doc json
)
SERVER mongo_server
OPTIONS (database 'prod', collection 'contributed_docs');
```

What do you think about this capability? Can you think of simpler/easier/better ways to add it?

**Comment by joaocc** [comment]
Hi. Any updates on this one? Thx

**Comment by MLinster** [comment]
Hi Simeon:

I think this could be avery interesting capability. Would love to discuss the bigger use case with you.

What would be a good time?

regards, Marc


> On Aug 22, 2015, at 10:38 PM, Simeon Simeonov <notifications@github.com> wrote:
> 
> mongo_fdw is great for ETL and interactive analytics with one catch: the current schema mapping approach does not seem to allow any way for all the data in a document to be retrieved without a priori knowing all top-level field names, which is important when all Mongo data must become available in SQL. Adding this capability would substantially increase the power of mongo_fdw.
> 
> One simple approach would be to reserve a special JSON field name, e.g., __doc for the contents of the entire document. Then, one could get the best of schema-based and schema-less processing, e.g.,
> 
> CREATE FOREIGN TABLE docs(
>     _id NAME,
>     author text,
>     created_at timestamptz,
>     updated_at timestamptz,
>     __doc json
> )
> SERVER mongo_server
> OPTIONS (database 'prod', collection 'contributed_docs');
> What do you think about this capability? Can you think of simpler/easier/better ways to add it?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/EnterpriseDB/mongo_fdw/issues/32>.
> 


-----------------------------------
Marc Linster, Ph.D.
SVP, Products and Services
Export Compliance Officer




Ph: +1 (617) 306 6059; Skype: marc.linster
www.enterprisedb.co <http://www.enterprisedb.com/>m <http://www.enterprisedb.com/>

**Comment by ssimeonov** [comment]
@MLinster what bigger use case are you referring to?

**Comment by MLinster** [comment]
I’d be interested to understand how you are planning to use the Postgres FDW with MongoDB (I assume thats as part FastIgnite?). Now that Mongo has started to use Postgres as part of its BI architecture (they use a Multicorn adapter), I am curious to understand the use case and the needs (Our FDW uses the native API, and we believe its a lot faster.).




> On Jan 10, 2016, at 10:43 PM, Simeon Simeonov <notifications@github.com> wrote:
> 
> @MLinster <https://github.com/MLinster> what bigger use case are you referring to?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/EnterpriseDB/mongo_fdw/issues/32#issuecomment-170425575>.
> 


-----------------------------------
Marc Linster, Ph.D.
SVP, Products and Services
Export Compliance Officer




Ph: +1 (617) 306 6059; Skype: marc.linster
www.enterprisedb.co <http://www.enterprisedb.com/>m <http://www.enterprisedb.com/>

**Comment by ssimeonov** [comment]
I was evaluating potentially using `mongo_fdw` at [Swoop](http://swoop.com) for an ETL use case but decided against it because of the lack of this particular capability.

**Comment by ahsanhadi** [comment]
Hi Joao,

This is an interesting capability to add to mongodb_fdw. I believe the idea
shared by Simeon does seem like an interesting one where we can add extra
json column to the foreign table which has all the data from the document.

This is marked as an enhancement request on mongdb_fdw github page. I can
discuss with product management to see if we can bump up the priority of
this feature request.

-- Ahsan


On Sun, Jan 10, 2016 at 2:27 AM, Joao C Costa <notifications@github.com>
wrote:

> Hi. Any updates on this one? Thx
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mongo_fdw/issues/32#issuecomment-170283649>
> .
>



-- 
Ahsan Hadi
Snr Director Product Development
EnterpriseDB Corporation
The Enterprise Postgres Company

Phone: +92-51-8358874
Mobile: +92-333-5162114

Website: www.enterprisedb.com
EnterpriseDB Blog: http://blogs.enterprisedb.com/
Follow us on Twitter: http://www.twitter.com/enterprisedb

This e-mail message (and any attachment) is intended for the use of the
individual or entity to whom it is addressed. This message contains
information from EnterpriseDB Corporation that may be privileged,
confidential, or exempt from disclosure under applicable law. If you are
not the intended recipient or authorized to receive this for the intended
recipient, any use, dissemination, distribution, retention, archiving, or
copying of this communication is strictly prohibited. If you have received
this e-mail in error, please notify the sender immediately by reply e-mail
and delete this message.

**Comment by joaocc** [comment]
Thx. That would be great!

**Comment by ahsanhadi** [comment]
Hi Guys,

We have been working on adding this full document retrieval functionality
to Mongodb fdw. Ibrar will commit this to mongodb_fdw github today, this
functionality will only be available in the new Mongo C driver not with the
legacy driver.

Please give it a test once it is committed and let us know if you find any
issues.

-- Ahsan


On Mon, Jan 11, 2016 at 6:56 PM, Joao C Costa <notifications@github.com>
wrote:

> Thx. That would be great!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mongo_fdw/issues/32#issuecomment-170557025>
> .
>



-- 
Ahsan Hadi
Snr Director Product Development
EnterpriseDB Corporation
The Enterprise Postgres Company

Phone: +92-51-8358874
Mobile: +92-333-5162114

Website: www.enterprisedb.com
EnterpriseDB Blog: http://blogs.enterprisedb.com/
Follow us on Twitter: http://www.twitter.com/enterprisedb

This e-mail message (and any attachment) is intended for the use of the
individual or entity to whom it is addressed. This message contains
information from EnterpriseDB Corporation that may be privileged,
confidential, or exempt from disclosure under applicable law. If you are
not the intended recipient or authorized to receive this for the intended
recipient, any use, dissemination, distribution, retention, archiving, or
copying of this communication is strictly prohibited. If you have received
this e-mail in error, please notify the sender immediately by reply e-mail
and delete this message.

**Comment by joaocc** [comment]
Great! I am currently on another assignment, but I will try to find some time to test this and provide some feedback. Thx!

**Comment by ahsanhadi** [comment]
Please let us know how you testing went...

**Comment by jduncanl** [comment]
> 
> 
> Hi Joao,
> 
> This is an interesting capability to add to mongodb_fdw. I believe the idea
> shared by Simeon does seem like an interesting one where we can add extra
> json column to the foreign table which has all the data from the document.
> 
> This is marked as an enhancement request on mongdb_fdw github page. I can
> discuss with product management to see if we can bump up the priority of
> this feature request.
> 
> -- Ahsan
> 
> On Sun, Jan 10, 2016 at 2:27 AM, Joao C Costa [notifications@github.com](mailto:notifications@github.com)
> wrote:
> 
> > Hi. Any updates on this one? Thx
> > —
> > Reply to this email directly or view it on GitHub
> > [#32 (comment)](https://github.com/EnterpriseDB/mongo_fdw/issues/32#issuecomment-170283649)
> > .
> 
> Ahsan Hadi
> Snr Director Product Development
> EnterpriseDB Corporation
> The Enterprise Postgres Company
> 
> Phone: +92-51-8358874
> Mobile: +92-333-5162114
> 
> Website: [www.enterprisedb.com](http://www.enterprisedb.com)
> EnterpriseDB Blog: http://blogs.enterprisedb.com/
> Follow us on Twitter: http://www.twitter.com/enterprisedb
> 
> This e-mail message (and any attachment) is intended for the use of the
> individual or entity to whom it is addressed. This message contains
> information from EnterpriseDB Corporation that may be privileged,
> confidential, or exempt from disclosure under applicable law. If you are
> not the intended recipient or authorized to receive this for the intended
> recipient, any use, dissemination, distribution, retention, archiving, or
> copying of this communication is strictly prohibited. If you have received
> this e-mail in error, please notify the sender immediately by reply e-mail
> and delete this message.

Hi, was this added ? 
Where can I find the documentation ? 
For me this is more important than extracting particular fields. One can always get the specific fields from the json, but one can't get what is not there. 
Best regards.
