### ISSUE TITLE
Updating install via PGXN (still based on citusdata/mongo_fdw)

### ISSUE THREAD

**Issue by joaocc** [EnterpriseDB/mongo_fdw#41]
Hi,
Are there any plans to allow for the latest version of mongo_fdw to be available via pgxn?
When I looked at http://pgxn.org/dist/mongo_fdw/, it's dated 2013-11-18, pgsql 9.2, and mentions it is released by citusdata.
Thx

**Comment by ahsanhadi** [comment]
On Sun, Jan 10, 2016 at 2:05 AM, Joao C Costa <notifications@github.com>
wrote:

> Hi,
> Are there any plans to allow for the latest version of mongo_fdw to be
> available via pgxn?
> When I looked at http://pgxn.org/dist/mongo_fdw/, it's dated 2013-11-18,
> pgsql 9.2, and mentions it is released by citusdata.
>
Yes we have requested the citusdata mongo_fdw on pgxn to be replaced by
mongodb_fdw from enterprisedb github. I will follow-up on this.


> Thx
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mongo_fdw/issues/41>.
>



-- 
Ahsan Hadi
Snr Director Product Development
EnterpriseDB Corporation
The Enterprise Postgres Company

Phone: +92-51-8358874
Mobile: +92-333-5162114

Website: www.enterprisedb.com
EnterpriseDB Blog: http://blogs.enterprisedb.com/
Follow us on Twitter: http://www.twitter.com/enterprisedb

This e-mail message (and any attachment) is intended for the use of the
individual or entity to whom it is addressed. This message contains
information from EnterpriseDB Corporation that may be privileged,
confidential, or exempt from disclosure under applicable law. If you are
not the intended recipient or authorized to receive this for the intended
recipient, any use, dissemination, distribution, retention, archiving, or
copying of this communication is strictly prohibited. If you have received
this e-mail in error, please notify the sender immediately by reply e-mail
and delete this message.

**Comment by jeevanchalke** [comment]
This seems very old. Closing for now. If you think there is still an issue, kind request to open a new issue.

Thanks
