### ISSUE TITLE
Error compiling the last Makefile command

### ISSUE THREAD

**Issue by shreyashah9** [EnterpriseDB/mongo_fdw#43]
gcc -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -fPIC -pie -I/usr/include/mit-krb5 -DLINUX_OOM_SCORE_ADJ=0 -fno-omit-frame-pointer -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -fpic -shared -o mongo_fdw.so connection.o option.o mongo_wrapper_meta.o mongo_fdw.o mongo_query.o json-c/json_util.o json-c/json_object.o json-c/json_tokener.o json-c/json_object_iterator.o json-c/printbuf.o json-c/linkhash.o json-c/arraylist.o json-c/random_seed.o json-c/debug.o -L/usr/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -L/usr/lib/mit-krb5 -L/usr/lib/x86_64-linux-gnu/mit-krb5  -Wl,--as-needed  -L/usr/local/lib -lssl -lcrypto -lrt -lmongoc-1.0 -lbson-1.0   
/usr/bin/ld: json-c/json_util.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
json-c/json_util.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make: *** [mongo_fdw.so] Error 1..

Please help to solve this issue..

**Comment by ibrarahmad** [comment]
Please try to clean before compiling.

make clean
make

On Fri, Jan 15, 2016 at 2:30 PM, shreyashah9 <notifications@github.com>
wrote:

> gcc -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat
> -Werror=format-security -fPIC -pie -I/usr/include/mit-krb5
> -DLINUX_OOM_SCORE_ADJ=0 -fno-omit-frame-pointer -Wall -Wmissing-prototypes
> -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels
> -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv
> -fexcess-precision=standard -g -fpic -shared -o mongo_fdwso connectiono
> optiono mongo_wrapper_metao mongo_fdwo mongo_queryo json-c/json_utilo
> json-c/json_objecto json-c/json_tokenero json-c/json_object_iteratoro
> json-c/printbufo json-c/linkhasho json-c/arraylisto json-c/random_seedo
> json-c/debugo -L/usr/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now
> -Wl,--as-needed -L/usr/lib/mit-krb5 -L/usr/lib/x86_64-linux-gnu/mit-krb5
> -Wl,--as-needed -L/usr/local/lib -lssl -lcrypto -lrt -lmongoc-10 -lbson-10
>
> /usr/bin/ld: json-c/json_utilo: relocation R_X86_64_32 against
> `rodatastr18' can not be used when making a shared object; recompile with
> -fPIC
> json-c/json_utilo: error adding symbols: Bad value
> collect2: error: ld returned 1 exit status
> make: *** [mongo_fdwso] Error 1
>
> Please help to solve this issue
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mongo_fdw/issues/43>.
>



-- 
Ibrar Ahmed
EnterpriseDB   http://www.enterprisedb.com

**Comment by shreyashah9** [comment]
Yes done with that command..Thank you very much
