### ISSUE TITLE
make install Error 

### ISSUE THREAD

**Issue by moshir** [EnterpriseDB/mongo_fdw#44]
Hi,

just getting the following error after trying to build 

```
`cc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -I/usr/include/mit-krb5 -fPIC -pie -DLINUX_OOM_SCORE_ADJ=0 -fno-omit-frame-pointer -fpic --std=c99 -Imongo-c-driver/src -Ijson-c -I. -I./ -I/usr/include/postgresql/9.4/server -I/usr/include/postgresql/internal -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/tcl8.6  -c -o connection.o connection.c
In file included from mongo_wrapper.h:20:0,
                 from connection.c:21:
mongo_fdw.h:21:20: fatal error: config.h: No such file or directory
 #include "config.h"
                    ^
compilation terminated.
make: *** [connection.o] Error 1

```

I'm running this on Ubuntu with Pg 9.4.5.

Any clue what's going wrong ?

**Comment by ibrarahmad** [comment]
Please use

./autogen.sh --with-legacy
make clean
make
make install

On Tue, Jan 26, 2016 at 1:56 PM, moshir <notifications@github.com> wrote:

> Hi,
>
> just getting the following error after trying to build
>
> `cc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -I/usr/include/mit-krb5 -fPIC -pie -DLINUX_OOM_SCORE_ADJ=0 -fno-omit-frame-pointer -fpic --std=c99 -Imongo-c-driver/src -Ijson-c -I -I/ -I/usr/include/postgresql/94/server -I/usr/include/postgresql/internal -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/tcl86  -c -o connectiono connectionc
> In file included from mongo_wrapperh:20:0,
>                  from connectionc:21:
> mongo_fdwh:21:20: fatal error: configh: No such file or directory
>  #include "configh"
>                     ^
> compilation terminated
> make: *** [connectiono] Error 1
>
>
> I'm running this on Ubuntu with Pg 945
>
> Any clue what's going wrong ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mongo_fdw/issues/44>.
>



-- 
Ibrar Ahmed
EnterpriseDB   http://www.enterprisedb.com

**Comment by moshir** [comment]
Ok, thank you, this works.
Might be interesting to include this in the doc install section for n000bs like myself :).
