### ISSUE TITLE
recent errors in make 

### ISSUE THREAD

**Issue by wdhutton** [EnterpriseDB/mongo_fdw#45]
src/mongoc/mongoc-write-concern.c: In function 'mongoc_write_concern_is_acknowledged':
src/mongoc/mongoc-write-concern.c:410:15: warning: 'mongoc_write_concern_get_fsync' is deprecated (declared at src/mongoc/mongoc-write-concern.c:100) [-Wdeprecated-declarations]
               mongoc_write_concern_get_fsync(write_concern) ||
               ^
src/mongoc/mongoc-write-concern.c: In function 'mongoc_write_concern_is_valid':
src/mongoc/mongoc-write-concern.c:434:4: warning: 'mongoc_write_concern_get_fsync' is deprecated (declared at src/mongoc/mongoc-write-concern.c:100) [-Wdeprecated-declarations]
    if ((mongoc_write_concern_get_fsync (write_concern) ||
    ^
  CC       src/mongoc/libmongoc_priv_la-mongoc-crypto.lo
src/mongoc/mongoc-crypto.c: In function 'mongoc_crypto_init':
src/mongoc/mongoc-crypto.c:32:11: error: 'MONGOC_CRYPTO_TYPE' undeclared (first use in this function)
    switch(MONGOC_CRYPTO_TYPE)
           ^
src/mongoc/mongoc-crypto.c:32:11: note: each undeclared identifier is reported only once for each function it appears in
make[1]: **\* [src/mongoc/libmongoc_priv_la-mongoc-crypto.lo] Error 1
make[1]: Leaving directory `/root/mongo-c-driver'
make: **\* [all-recursive] Error 1

**Comment by ahsanhadi** [comment]
Is this still an active issue?

**Comment by wdhutton** [comment]
No thanks
