### ISSUE TITLE
[removed]

### ISSUE THREAD

**Issue by begriffs** [EnterpriseDB/mongo_fdw#46]

**Comment by begriffs** [comment]
I'm sorry, there was a miscommunication on my end and I am closing this issue.

**Comment by ahsanhadi** [comment]
On Wed, Mar 2, 2016 at 4:55 AM, Joe Nelson <notifications@github.com> wrote:

> Hi maintainers, thanks for the work you’ve done on the mongo_fdw project.
> We at Citus no longer maintain our original upstream repo at
> https://github.com/citusdata/mongo_fdw and are wondering if we can
> transfer ownership to you? This way the pull requests, issues, stars and
> watchers will move over to your fork.
>
> Let me know, and thanks again for keeping the project going.
>

Hi Joe,

We have requested taking the ownership of mongodb fdw several time before.
So yes we are ready to take the owner, the mongodb_fdw projects is
available from the following github location...

https://github.com/citusdata/mongo_fdw

We also need to update this on PGXN so anyone downloading mongodb_fdw from
PGXN will download the latest one from the above location.

-- Ahsan


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mongo_fdw/issues/46>.
>



-- 
Ahsan Hadi
Snr Director Product Development
EnterpriseDB Corporation
The Enterprise Postgres Company

Phone: +92-51-8358874
Mobile: +92-333-5162114

Website: www.enterprisedb.com
EnterpriseDB Blog: http://blogs.enterprisedb.com/
Follow us on Twitter: http://www.twitter.com/enterprisedb

This e-mail message (and any attachment) is intended for the use of the
individual or entity to whom it is addressed. This message contains
information from EnterpriseDB Corporation that may be privileged,
confidential, or exempt from disclosure under applicable law. If you are
not the intended recipient or authorized to receive this for the intended
recipient, any use, dissemination, distribution, retention, archiving, or
copying of this communication is strictly prohibited. If you have received
this e-mail in error, please notify the sender immediately by reply e-mail
and delete this message.
