### ISSUE TITLE
C driver version: conflicting information

### ISSUE THREAD

**Issue by taylorterry3** [EnterpriseDB/mongo_fdw#48]
I'm trying to troubleshoot some queries that run extremely slow and others that halt at 300s with no results, and I want to make sure I'm using the most recent Mongo C driver. The docs suggest that the C driver version is locked to 0.8 (https://github.com/EnterpriseDB/mongo_fdw/blob/master/README.md#L10), but the commit hash of the linked submodule looks up to date at 1.3.4. From what I can tell my setup is using 1.3.4, but is there any way to get mongo_fdw to spit out the driver version it's using? Thanks!

**Comment by ahsanhadi** [comment]
hi,
You can take a look at autogen.sh script that is used to pull and build the mongo drivers, from what i can see it is getting the 1.3.1 mongo driver...

Can you please share a test case with query that is taking more then 300s to run and returns without an error?

-- Ahsan

**Comment by taylorterry3** [comment]
Got it re: the driver version. Happy to do a PR if you want updated docs.

In the time since I opened this issue we've moved to the wiredtiger engine, so I can't reproduce my failed queries. Thanks for the help!
