### ISSUE TITLE
Is there any way to specify the authentication database

### ISSUE THREAD

**Issue by acheccuc** [EnterpriseDB/mongo_fdw#51]
In our clusters the authentication database is separated from the database the user create collections in. I have browsed the source code, but haven't found any option to specify both.
Could you please suggest any method?

**Comment by ahsanhadi** [comment]
Can you please clarify your requirement with a test case? Where do you want to specify both databases when you create the foreign table?

**Comment by acheccuc** [comment]
Hi Ahsan,
thanks for looking into that. I would logically keep it with the user mapping, since it's part of the authentication and authorization phase rather than database work.

Just to give you an example, we use this kind of command line with the mongo shell:

mongo --host <HOSTNAME> --username <USER> --password <PASSWD> -- authenticationDatabase admin <DATABASE_NAME>

What happens is that USER authenticates against the admin database, where a role is applied which grants privileges for that USER on the <DATABASE_NAME> database.

Thanks
Alessio

**Comment by ahsanhadi** [comment]
Thanks for your response. This is a new feature request. I need to discuss the priority of this with our product management...

**Comment by acheccuc** [comment]
Checking the opened issues I see that the same request was filed on 12 Mar 2015 as #26. They should probably be merged....

**Comment by ahsanhadi** [comment]
Agreed...I will go ahead and update #26....

Unfortunately this is still not prioritised due to resource constraint but it is still on the radar...

**Comment by rotten** [comment]
I think it would be great if we could just pass a mongodb url:

https://docs.mongodb.com/manual/reference/connection-string/

Then we can connect to a replica set, use ssl, use an authentication database, and configure other tunables as they come up or get dropped by the MongoDB development team without having to deal with a significant recoding effort on the FDW to support one connection feature or another.

Not being able to use an alternate authentication database is a show stopper for us using this FDW.

**Comment by acheccuc** [comment]
I have tried to install the latest version, given that issue #26 has been marked as Closed with the following comment:

"In Meta driver the connection string "URI" already has database option, so it should work."

I don't see how to specify a MongoDB URI to connect, according to the docs included with the FDW.
Could you please help or give me any clue whether this issue has been tackled?

**Comment by petroswork** [comment]
https://github.com/EnterpriseDB/mongo_fdw/issues/77 works for me, thanks.
