### ISSUE TITLE
Make error - config.h no such file directory

### ISSUE THREAD

**Issue by rendybjunior** [EnterpriseDB/mongo_fdw#54]
I did git clone recursive, however when I do make, this error came up

```
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -I/usr/include/mit-krb5 -fPIC -pie -fno-omit-frame-pointer -fpic --std=c99 -Imongo-c-driver/src -Ijson-c -I. -I./ -I/usr/include/postgresql/9.5/server -I/usr/include/postgresql/internal -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/tcl8.6  -c -o connection.o connection.c
In file included from mongo_wrapper.h:20:0,
                 from connection.c:21:
mongo_fdw.h:21:20: fatal error: config.h: No such file or directory
 #include "config.h"
                    ^
compilation terminated.
make: *** [connection.o] Error 1
```

What should I do?

**Comment by ibrarahmad** [comment]
Use these command to compile the code

./autogen.sh --with-legacy
make

On Wed, Jun 8, 2016 at 8:27 AM, Rendy Bambang Junior <
notifications@github.com> wrote:

> I did git clone recursive, however when I do make, this error came up
>
> gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -I/usr/include/mit-krb5 -fPIC -pie -fno-omit-frame-pointer -fpic --std=c99 -Imongo-c-driver/src -Ijson-c -I. -I./ -I/usr/include/postgresql/9.5/server -I/usr/include/postgresql/internal -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/tcl8.6  -c -o connection.o connection.c
> In file included from mongo_wrapper.h:20:0,
>                  from connection.c:21:
> mongo_fdw.h:21:20: fatal error: config.h: No such file or directory
>  #include "config.h"
>                     ^
> compilation terminated.
> make: *** [connection.o] Error 1
>
> What should I do?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/EnterpriseDB/mongo_fdw/issues/54>, or mute the thread
> <https://github.com/notifications/unsubscribe/ADbS8ovRaO_dr2znYTXkP9UBXoG9QlT1ks5qJja-gaJpZM4Iwj9N>
> .
>



-- 
Ibrar Ahmed
EnterpriseDB   http://www.enterprisedb.com

**Comment by ahsanhadi** [comment]
rendy, is it working for you...can i close the case?
