### ISSUE TITLE
openssl/bio.h 

### ISSUE THREAD

**Issue by rotten** [EnterpriseDB/mongo_fdw#65]
When running `autogen.sh --with-master` on a Mac with Brew based gcc, openssl, and similar supporting libraries, we throw the following error:

> ./src/mongoc/mongoc-ssl-private.h:25:10: fatal error: 'openssl/bio.h' file not found

The solution is to set this environment variable before running autogen.sh:
`$  export CPPFLAGS="-I/usr/local/opt/openssl/include"`

**Comment by andreasscherbaum** [comment]
Is this still the case?

**Comment by vaibhavdalvi93** [comment]
@rotten , Are you still facing this issue? Can you please close this ticket if issue has been resolved?

**Comment by rotten** [comment]
I am no longer using either MongoDB or a Mac, so I cannot test this.  Since no one else has chimed in, either my workaround above solved it for them, or the problem has gone away with the newer macs and/or newer openssl versions.  We can close this as far as I'm concerned.

**Comment by jeevanchalke** [comment]
Closing per @rotten comment.
