### ISSUE TITLE
No return from foreign table 

### ISSUE THREAD

**Issue by dessaber** [EnterpriseDB/mongo_fdw#70]
Hello,

I try to set up mongo_fdw on my Amazon EC2 t2.medium instance, Ubuntu 16.04. Version of PostgreSQL is 9.6, MongoDB - 3.4. I followed all installation instructions, and at first I had an error described here:

[https://github.com/EnterpriseDB/mongo_fdw/issues/37]()

I fixed it with @andreabat's suggestion. Now all of mongo_fdw's commands work, I can see mongo_fdw in pg_extension, but it seems like I can't really connect to my MongoDB. Selects from my foreign table return no rows. Foreign server's IP is 127.0.0.1, port is 27017. I used my MongoDB username and password to create user mapping. First column of the table is _id with NAME type. Collection with the same name exists in MongoDB in admin database, and I specified it in create foreign table's options clause. 

Is there a way to fix it? What info can I provide to you guys, so this situation will be more clear?

**Comment by ahsanhadi** [comment]
Hi,

Are you still facing the connectivity issue?  Can you telnet the server port running mongodb? Do this from the machine running PG.
