### ISSUE TITLE
Can't connect to mongo router

### ISSUE THREAD

**Issue by zard14** [EnterpriseDB/mongo_fdw#81]
I build a mongo router,  and this tool can't connect to the mongo router.
When I connect to single node, it works, but when I connect to the mongo router, 
postgresql and MongoDb didn't throw out any log message

my single node
192.168.1.100  port 27017

router node
192.168.1.100 port 27019

**Comment by gabbasb** [comment]
Are you saying that when MongoDB is run on 192.168.1.100:27017, mongo_fdw connects and works fine and when you run it on the same computer but with a different port i.e. 192.168.1.100:27019 mongo_fdw is unable to connect to the MongoDB Server?

**Comment by zard14** [comment]
I found the problem finally. Because my default login account will log in to admin database, and the test collection in another database like "test",  I should put in the login account belong to that database, then it works.
