### ISSUE TITLE
could not retrieve document count for collection  cold not collect statistics about foreign table

### ISSUE THREAD

**Issue by fanhongli** [EnterpriseDB/mongo_fdw#87]
could not retrieve document count for collection

cold not collect statistics about foreign table

**Comment by ahsanhadi** [comment]
Can you please share a complete test case?

**Comment by fanhongli** [comment]
analyze table1

**Comment by fanhongli** [comment]
i want to use parallel to mongodb  "  group by  "

**Comment by fanhongli** [comment]
i found it in  mongo_wrapper_meta.c 
MongoAggregateCount 
if (bson_iter_init_find(&it, reply, "n")){
 count = BsonIterDouble(&it); 


that was verry .....

**Comment by fanhongli** [comment]
it should change to 
count = BsonIterDouble(&it);
			   if( count==0 ) {
				   count = 	BsonIterInt32(&it);			   
			   }
