### ISSUE TITLE
postgresql 10  is  ready for mongo_fdw ? 

### ISSUE THREAD

**Issue by fanhongli** [EnterpriseDB/mongo_fdw#88]
postgresql 10  is  ready for mongo_fdw ?

**Comment by ibrarahmad** [comment]
Only compilation issue fixed.

**Comment by andreasscherbaum** [comment]
The Makefile ( https://github.com/EnterpriseDB/mongo_fdw/blob/master/Makefile ) still checks for PostgreSQL 9.3, 9.4, 9.5 or 9.6. 10.0 is not working.
